##TESTS:

#### TOKEN (TEST ONLY)
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE1LCJlbWFpbCI6Imp1cmVAZ21haWwuY29tIiwiaWF0IjoxNzE1Nzc1NDE4LCJleHAiOjE3MTU3NzYzMTh9.Xcp2jkO-kOLdjOfL-B2O6dOK1wCq4Un2D4x-1_xZISE

### POST /auth/register
POST http://localhost:8080/auth/signup HTTP/1.1
Content-Type: application/json

{
  	"firstName": "John",
	"lastName": "Johnson",
	"email": "john@gmail.com",
  	"password": "John123!",
  	"confirm_password": "John123!",
	"this_field_should_not_be_passed": "filtered_variable"
}

### POST /auth/login
POST http://localhost:8080/auth/login HTTP/1.1
Content-Type: application/json

{
  	"email": "john@gmail.com",
  	"password": "John123!"
}

### POST /auth/signout
POST http://localhost:8080/auth/signout HTTP/1.1
Content-Type: application/json

{
  	"email": "john@gmail.com",
  	"password": "John123!"
}

### GET /me
GET http://localhost:8080/me HTTP/1.1
Content-Type: application/json
Authorization: {{token}} 

### GET /me/upload-image
POST http://localhost:8080/me/upload-image HTTP/1.1
#### Test with Postman: Body: key: 'image' (File), value: 'test_image.png' (dont forget to Authenticate)

### PATCH /me/edit
PATCH http://localhost:8080/me/edit HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
  	"firstName": "Not Johnn",
	"lastName": "Johnson",
	"email": "john@gmail.com",
  	"password": "John123456!"
}

### GET /me/update-password
PATCH http://localhost:8080/me/update-password HTTP/1.1
Content-Type: application/json
Authorization: {{token}} 

{
  	"firstName": "Johnny",
	"lastName": "Johnsssss",
	"email": "john@gmail.com",
  	"password": "John12345!",
  	"confirm_password": "John12345!"
}


### GET /me/auctions
GET http://localhost:8080/me/auctions HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

### GET /me/auction
POST http://localhost:8080/me/auction HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
	"title": "new auction with image",
	"currentPrice": 200,
	"status": "new status",
	"duration": "2024-05-15T12:30:00",
	"image": "new_image.png",
	"userId": 0
}

### POST /me/auction/:id/upload-image
POST http://localhost:8080/me/auction/21/upload-image HTTP/1.1
#### Test with Postman: Body: key: 'image' (File), value: 'test_image.png' (dont forget to Authenticate)

### GET /me/auction/:id
PATCH http://localhost:8080/me/auction/13 HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
	"title": "same title",
	"description": "bla bla bla",
	"status": "status changeD",
	"duration": "2024-06-15T12:30:00",
	"image": "new_new_image.png",
	"userId": 0
}

### GET /me/bids
GET http://localhost:8080/me/bids HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

### GET /me/bids/won
GET http://localhost:8080/me/bids/won HTTP/1.1
Content-Type: application/json
Authorization: {{token}}


### GET all auctions
GET http://localhost:8080/auctions HTTP/1.1

### GET one auction
GET http://localhost:8080/auctions/3 HTTP/1.1

### GET all bids from auction
GET http://localhost:8080/auctions/3/bids HTTP/1.1

### POST bid on auction
POST http://localhost:8080/auctions/2/bid HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
	"price": 200,
	"status": "status changeD",
	"userId": 0,
	"auctionId": 0
}
