##TESTS:

#### TOKEN (TEST ONLY)
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE0LCJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwiaWF0IjoxNzEzNjAwNTQ3LCJleHAiOjE3MTM2MDE0NDd9.GKfxusQjrW3erg8tKXssK5m1qh-geoJk5_lprCUziP8

### POST /auth/register
POST http://localhost:8080/auth/signup HTTP/1.1
Content-Type: application/json

{
  	"firstName": "John",
	"lastName": "Johnson",
	"email": "john@gmail.com",
  	"password": "John123!",
  	"confirm_password": "John123!",
	"this_field_should_not_be_passed": "filtered_variable"
}

### POST /auth/login
POST http://localhost:8080/auth/login HTTP/1.1
Content-Type: application/json

{
  	"email": "john@gmail.com",
  	"password": "John123!"
}

### POST /auth/signout
POST http://localhost:8080/auth/signout HTTP/1.1
Content-Type: application/json

{
  	"email": "john@gmail.com",
  	"password": "John123!"
}


### GET /me
GET http://localhost:8080/me HTTP/1.1
Content-Type: application/json
Authorization: {{token}} 

### GET /me/upload-image
POST http://localhost:8080/me/upload-image HTTP/1.1
Content-Type: multipart/form-data boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer {{token}}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="test_image.png"
Content-Type: image/png

0000000000000000000010000
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### PATCH /me/edit
PATCH http://localhost:8080/me/edit HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
  	"firstName": "Not John",
	"lastName": "Not Johnson",
	"email": "john@gmail.com",
  	"password": "John123456!",
	"image": "new_path"
}

### GET /me/update-password
PATCH http://localhost:8080/me/update-password HTTP/1.1
Content-Type: application/json
Authorization: {{token}} 

{
  	"firstName": "Johnny",
	"lastName": "Johnsssss",
	"email": "john@gmail.com",
  	"password": "John1234!",
  	"confirm_password": "John1234!"
}

### GET /me/auctions
GET http://localhost:8080/me/auctions HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

### GET /me/auction
POST http://localhost:8080/me/auction HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

### GET /me/auction/:id
PATCH http://localhost:8080/me/auction/:id HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

### GET /me/bids
GET http://localhost:8080/me/bids HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

### GET /me/bids/won
GET http://localhost:8080/me/bids/won HTTP/1.1
Content-Type: application/json
Authorization: {{token}}


### GET /auctions
GET http://localhost:8080/auctions HTTP/1.1

### GET /auctions/:id
GET http://localhost:8080/auctions/:id HTTP/1.1

### GET /auctions/:id/bid
GET http://localhost:8080/auctions/:id/bid HTTP/1.1
